# Vectors

In [2]:
import numpy as np

In [3]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

Dot-Product (Skalarprodukt, inneres Produkt)
- relates two vectors to a scalar
$$
\vec{a} \cdot \vec{b} = |\vec{a}| |\vec{b}| \cos \theta
$$

In [4]:
dot1 = np.dot(vec1, vec2)
print(dot1)

32


Cross-Product (Kreuzprodukt)
- calculates a vector that is perpendicular to vector A and B
$$
|\vec{a} \times \vec{b}| = |\vec{a}| |\vec{b}| \sin \theta
$$

In [5]:
cross1 = np.cross(vec1, vec2)
print(cross1)

[-3  6 -3]


Norm

In [6]:
norm1 = np.linalg.norm(vec1)
print(norm1)

norm2 = np.sqrt(vec1[0]**2+vec1[1]**2+vec1[2]**2)
print(norm2)

norm3 = np.sqrt(np.sum(vec1**2))
print(norm3)

3.7416573867739413
3.7416573867739413
3.7416573867739413


# Matrices

In [7]:
mat1 = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])
mat2 = np.array([[1, 1, 1], [0, 2, 2], [0, 0, 3]])

Matrix-Multiplication

In [8]:
matmul1 = np.matmul(mat1, mat2)
print(matmul1)

[[  1  -3   6]
 [ -4   6 -12]
 [  7  -9  18]]


In [9]:
matmul2 = np.matmul(mat2, mat1)
print(matmul2)

[[  4  -5   6]
 [  6  -6   6]
 [ 21 -24  27]]


Determinant and Inverse

In [10]:
det1  = np.linalg.det(mat2)
print(det1)

6.0


In [11]:
inv1 = np.linalg.inv(mat2)
print(inv1)

[[ 1.         -0.5         0.        ]
 [ 0.          0.5        -0.33333333]
 [ 0.          0.          0.33333333]]
